#dubbo.application.name=springboot-consumer-annotation
#dubbo.registry.protocol=zookeeper
#dubbo.registry.address=114.55.146.162:2181

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/v16?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
   username: root
   password: sa
   driver-class-name: com.mysql.jdbc.Driver
 redis:
    host: 114.55.146.162
    port: 6379
    password: caomeng
    jedis:
      pool:
        max-active: 66

dubbo:
  application:
    name: product-privder
  registry:
    protocol: zookeeper
    address: 114.55.146.162:2181
  protocol:
      port: 20881

server:
  port: 8081



