
dubbo:
  registry:
    protocol: zookeeper
    address: 114.55.146.162:2181
  application:
    name: web-item
server:
  port: 9094
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/v16?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    port: 5672
    username: caomeng
    password: caomeng
    virtual-host: /caomeng
    host: 10.36.8.8